description: >
  Default executor, with Docker cimg/base
parameters:
  tag:
    default: stable
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/base/tags
    type: string
docker:
  - image: cimg/base:<< parameters.tag >>
